Primeira versao
dadosjusbr/proto pull request #2
Opened 2021-07-30 13:09 UTC by joeberth

Criando os arquivos em golang e python

2021-08-01 19:00 UTC, danielfireman requested changes
Por que você removeu os campos requeridos? Lembre-se que não preencher valores importantes foi uma das principais causas de erro.

2021-08-01 19:00 UTC, danielfireman reviewed
Gostei bastante dos nomes!

2021-08-02 03:35 UTC, joeberth commented
> Por que você removeu os campos requeridos? Lembre-se que não preencher valores importantes foi uma das principais causas de erro.

Fireman, até onde eu entendi, 'required' e 'optional' foram removidos com a chegada da syntax 'proto3'
https://newbedev.com/why-required-and-optional-is-removed-in-protocol-buffers-3
Por isso que eu removi. Podemos seguir assim ou alguma outra sugestão?

2021-08-02 11:33 UTC, danielfireman commented
Entendi. Não sabia. Nós só temos que lembrar de adicionar as checagens.

Em seg, 2 de ago de 2021 00:35, Joeberth Souza ***@***.***>
escreveu:

> Por que você removeu os campos requeridos? Lembre-se que não preencher
> valores importantes foi uma das principais causas de erro.
>
> Fireman, até onde eu entendi, 'required' e 'optional' foram removidos com
> a chegada da syntax 'proto3'
>
> https://newbedev.com/why-required-and-optional-is-removed-in-protocol-buffers-3
> Por isso que eu removi. Podemos seguir assim ou alguma outra sugestão?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/dadosjusbr/proto/pull/2#issuecomment-890686696>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACEJMQZXVJKDJL5H6IIUYYDT2YHABANCNFSM5BIP5RMA>
> .
>

2021-08-02 11:36 UTC, danielfireman approved these changes

2021-08-02 16:36 UTC, merged