Adiciona mensagem sobre índice ao proto
dadosjusbr/proto pull request #5
Opened 2021-09-28 12:35 UTC by joaolgm

Criação da mensagem sobre o metadado do índice

2021-09-28 14:38 UTC, danielfireman requested changes

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +    Metadado metadado = 4;
```suggestion
    Metadados metadados = 4;
```

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +message Metadado {
```suggestion
message Metadados {
```

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +    int32 id_orgao = 2;
Essas informações não são necessárias, pois estão na coleta.

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +    enum FormaDeAcesso {
Por favor, documentar todos os campos. Pode pegar do documento que criamos e melhorar, quando necessário.

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +    FormaDeAcesso acesso_ao_dado = 5;
```suggestion
    FormaDeAcesso acesso = 5;
```

2021-09-28 14:38 UTC, danielfireman commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
Aqui não deveria ser do tipo OpcoesDetalhamento?

2021-09-28 15:10 UTC, joaolgm commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
remuneracao_base é  uma coluna única mesmo. Ela faz parte de uma soma que resulta em Total de Rendimentos Brutos, caso esse total seja adicionado ao índice será do tipo OpcoesDetalhamento(por ser uma soma de diversas colunas, entre elas: férias, abono, gratificação natalina etc). Deve ser adicionado?

2021-09-28 15:12 UTC, joaolgm commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
Se não me engano, a gente chama essas colunas de _funds_

2021-09-28 18:16 UTC, danielfireman commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
Essas classificações não existem mais no leiaute v2, João. Poderia dar uma olhada, por favor? Em particular, é um conjunto de campos que classificaremos de acordo com o [TipoReceita](https://github.com/dadosjusbr/proto/blob/main/coleta/coleta.proto#L73).

2021-09-29 13:38 UTC, joaolgm commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
Verdade. Mas o índice de transparência continua com os mesmos parametros, certo?

2021-09-29 13:44 UTC, danielfireman commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
O que você quer dizer com parâmetros?

2021-09-29 13:56 UTC, joaolgm commented on coleta/coleta.proto
> +    bool remuneracao_base = 12;
A gente continua olhando pros mesmos pontos(não requer login, estritamente tabular, tem lotação, tem cargo, etc), que já foram discutidos, na hora de pontuar um órgão?

2021-09-29 14:37 UTC, danielfireman requested changes

2021-09-29 14:37 UTC, danielfireman commented on coleta/coleta.proto
> +        ACESSO_DIRETO = 0;
Documentar cada uma dessas formas de acesso.

2021-09-29 14:37 UTC, danielfireman commented on coleta/coleta.proto
> +    bool formato_consistente = 5; // Órgão alterou a forma de expor seus dados entre os meses?
```suggestion
    bool formato_consistente = 5; // Órgão alterou a forma de expor seus dados entre o mês em questão e o mês anterior?
```

2021-09-29 14:37 UTC, danielfireman commented on coleta/coleta.proto
> +    bool nao_requer_login = 0; // É necessário login para coleta dos dados?
Tem certeza que essa numeração deve começar do zero? Viu isso na documentação? Perguntando pois em nenhuma das outras mensagens começamos do zero.

2021-09-29 15:00 UTC, danielfireman approved these changes

2021-09-29 15:04 UTC, merged